### ISSUE TITLE
Crash with Circle Macro + one nub when Apply Edit is used.

### ISSUE THREAD

**Issue by Sigillatus** [TheDwarfHorde/DHShapeMaker#2]
As discovered & reported by Pixey:

With Circle Macro enabled...
Add ONE nub
Hit Apply Edit
CRASH!

Exception details:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ShapeMaker.EffectPluginConfigDialog.ApplyBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by technorobbo** [comment]
Fixed

**Comment by technorobbo** [comment]
Im forgot to close
